trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  application: TemperatureController
  appdir: examples/$(application)
  application_lower: $[lower(variables['application'])]

steps:
- template: steps/checkout.yaml
- template: steps/build.yaml
- template: steps/publish-deb.yaml
- template: steps/publish-feed.yaml
