trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  Solution.Version: 0.0.0-ci-$(Build.BuildId)
  Solution.ApplicationLocation: examples

steps:
- template: steps/checkout.yaml
- template: steps/build.yaml
  parameters: 
    Application: TemperatureController
- template: steps/publish-deb.yaml
