trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  application: TemperatureController
  appdir: examples/$(application)
  applower: $[lower(variables['application'])]
  appver: 0.0.0-ci-$(Build.BuildId)
  appdescription: "Example temperature controller for Azure IoT"

steps:
- template: steps/checkout.yaml
- template: steps/build.yaml
- template: steps/publish-deb.yaml
- template: steps/publish-feed.yaml
