trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  application: TemperatureController
  appdir: examples/$(application)
  buildversion: ci-$(Build.BuildNumber)

steps:
- template: steps/checkout.yaml
- template: steps/version.yaml
- template: steps/build.yaml
- template: steps/publish.yaml
