trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  Application.Name: TemperatureController
  Application.Directory: examples/$(application)
  Application.LowerName: $[lower(variables['Application.Name'])]
  Application.Version: 0.0.0-ci-$(Build.BuildId)
  Application.Description: "Example temperature controller for Azure IoT"

steps:
- template: steps/checkout.yaml
- template: steps/build.yaml
- template: steps/publish-deb.yaml
- template: steps/publish-feed.yaml
