[provisioning]
source = "dps"
global_endpoint = "https://global.azure-devices-provisioning.net"
id_scope = "$(IdScope)"

[provisioning.attestation]
method = "symmetric_key"
registration_id = "$(DeviceId)"
symmetric_key = { value = $(DeviceKey) }