###
#
# (4) Generate a config.toml file for the edge device
#
##

# Ensure needed env vars are set
$vars = @{
    DEVICEID = "Your assigned ID for the single device. I recommend using the MAC address"
    DEVICEKEY = "Device-specific key, generated by MakeDeviceKey.ps1" 
    IDSCOPE = "ID Scope for this device provisioning service"
}

foreach( $var in $vars.GetEnumerator() )
{
    if (-not (Test-Path env:$($var.key))) 
    { 
        Write-Output "Please set env:$($var.Key) to $($var.Value)"
        Exit 
    }
}

# List of tokens to replace
$tokenList = @{
    DeviceId = $env:DEVICEID
    DeviceKey = $env:DEVICEKEY
    IdScope = $env:IDSCOPE
}

# Replace the tokens
$manifest = Get-Content -Path config.template.toml -RAW
foreach( $token in $tokenList.GetEnumerator() )
{
    $pattern = '\$\({0}\)' -f $token.key
    $manifest = $manifest -replace $pattern, $token.Value
}

# Save out the generated result
$manifest > config.toml

# Display to user
Get-Content config.toml

#
# Copy the resulting config.toml file to the device
#