FROM mcr.microsoft.com/dotnet/runtime:7.0
#RUN dotnet publish -c Release -o bin/out
COPY ./bin/out ./
RUN rm config.toml

RUN useradd -ms /bin/bash moduleuser
USER moduleuser

ENTRYPOINT ["dotnet", "InfluxDbTemperatureController.dll"]